# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

  elastic.client.factory:
    class: Elasticsearch\ClientBuilder
    factory: [Elasticsearch\ClientBuilder, create]
    calls:
      - [setHosts, ["%elastic.hosts%"]]

  elastic.client:
    class: Elasticsearch\Client
    factory: ["@elastic.client.factory", build]

  index_item.item_retriever:
    class: AppBundle\Services\ItemRetriever
    arguments:
      - "@doctrine.orm.entity_manager"

  index_item.item_indexer:
    class: AppBundle\Services\ItemIndexer
    arguments:
      - "@elastic.client"
      - "@uvinum.api_handler"

  index_item:
    class: AppBundle\Services\IndexItem
    arguments:
      - "@index_item.item_retriever"
      - "@index_item.item_indexer"

  index_all:
    class: AppBundle\Services\IndexAll
    arguments:
      - "@index_item.item_retriever"
      - "@index_item.item_indexer"

  index_topselling:
    class: AppBundle\Services\IndexTopSelling
    arguments:
      - "@index_item.item_indexer"

  index_item.message_handler:
    class: AppBundle\Infrastructure\IndexItemMessageHandler
    arguments:
      - "@index_item"

  uvinum.api_handler:
    class: AppBundle\Services\UvinumApiHandler
    arguments:
      - "%uvinum_api_key%"
